services:
  - type: web
    name: hc-dance-classes
    env: python
    region: oregon
    plan: free
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT --workers 2
    buildCommand: pip install -r backend/requirement.txt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
